### ISSUE TITLE
Java / NF dependency conflict in pipeline Gitpod environment

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1428]
### Description of the bug

When trying to use the latest edge version of NF for testing of nf-core/rnaseq (`master`) on Gitpod it appears that there is a dependency conflict between Java and NF indicating that we may need to bump the version of Java available in the Gitpod environment.

```
java.lang.UnsupportedClassVersionError: nextflow/cli/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

### Command used and terminal output

```console
$ NXF_VER=22.02.1-edge nextflow run main.nf -profile test,docker --outdir ./results -resume

Picked up JAVA_TOOL_OPTIONS:  -Xmx6871m
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:22.02.1-edge
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:22.02.1-edge
CAPSULE: Downloading dependency org.jsoup:jsoup:jar:1.14.3
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:22.02.1-edge
CAPSULE: Downloading dependency dev.failsafe:failsafe:jar:3.1.0
Picked up JAVA_TOOL_OPTIONS:  -Xmx6871m
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: nextflow/cli/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```
```


### System information

_No response_

**Comment by drpatelh** [comment]
Paolo confirmed that the min version needs to be Java 11 in the container.
