### ISSUE TITLE
nf-core list hiccup

### ISSUE THREAD

**Issue by vibbits** [nf-core/tools#180]
Hello, 
Here are the commands I used and the errors I get: 

<details>
<summary>Click to expand installation log</summary>

```
Orens-MacBook-Pro:nf-core-tools oren$ pip3 install nf-core
Collecting nf-core
  Downloading https://files.pythonhosted.org/packages/9a/10/d4419093c0cc66d856df1a45c3b5c4548600d403596afbf77224dff4b571/nf-core-1.2.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 456kB/s 
Collecting cookiecutter (from nf-core)
  Downloading https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1.6.0-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 252kB/s 
Collecting click (from nf-core)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 317kB/s 
Collecting GitPython (from nf-core)
  Downloading https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl (448kB)
    100% |████████████████████████████████| 450kB 625kB/s 
Collecting pyyaml (from nf-core)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 450kB/s 
Collecting requests (from nf-core)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 394kB/s 
Collecting requests_cache (from nf-core)
  Downloading https://files.pythonhosted.org/packages/00/62/9e45a38988cb48c474805a1626439f4d9a486a042bd077af888fa8b17a64/requests_cache-0.4.13-py2.py3-none-any.whl
Collecting tabulate (from nf-core)
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Collecting poyo>=0.1.0 (from cookiecutter->nf-core)
  Downloading https://files.pythonhosted.org/packages/e0/16/e00e3001007a5e416ca6a51def6f9e4be6a774bf1c8486d20466f834d113/poyo-0.4.2-py2.py3-none-any.whl
Collecting future>=0.15.2 (from cookiecutter->nf-core)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 383kB/s 
Collecting binaryornot>=0.2.0 (from cookiecutter->nf-core)
  Downloading https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting jinja2-time>=0.1.0 (from cookiecutter->nf-core)
  Downloading https://files.pythonhosted.org/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl
Collecting jinja2>=2.7 (from cookiecutter->nf-core)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting whichcraft>=0.4.0 (from cookiecutter->nf-core)
  Downloading https://files.pythonhosted.org/packages/60/8a/5c52e30e11672f7e3aa61f348ddae443d122bcd96bc8b785ac76dbae944b/whichcraft-0.4.1-py2.py3-none-any.whl
Collecting gitdb2>=2.0.0 (from GitPython->nf-core)
  Downloading https://files.pythonhosted.org/packages/a9/fb/d3afc4e2a8d506a07af19f125f7a473ae1b56f942ed2ba80776eb8ae23b1/gitdb2-2.0.4-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 244kB/s 
Collecting certifi>=2017.4.17 (from requests->nf-core)
  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
    100% |████████████████████████████████| 153kB 342kB/s 
Collecting urllib3<1.24,>=1.21.1 (from requests->nf-core)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 522kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->nf-core)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->nf-core)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 506kB/s 
Collecting arrow (from jinja2-time>=0.1.0->cookiecutter->nf-core)
  Downloading https://files.pythonhosted.org/packages/e0/86/4eb5228a43042e9a80fe8c84093a8a36f5db34a3767ebd5e1e7729864e7b/arrow-0.12.1.tar.gz (65kB)
    100% |████████████████████████████████| 71kB 796kB/s 
Collecting MarkupSafe>=0.23 (from jinja2>=2.7->cookiecutter->nf-core)
  Using cached https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython->nf-core)
  Downloading https://files.pythonhosted.org/packages/0f/14/e3112808b727f72df9531fc2f00b84d4966e66001748b6883a21c767e902/smmap2-2.0.4-py2.py3-none-any.whl
Collecting python-dateutil (from arrow->jinja2-time>=0.1.0->cookiecutter->nf-core)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->arrow->jinja2-time>=0.1.0->cookiecutter->nf-core)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: nf-core, pyyaml, tabulate, future, arrow, MarkupSafe
  Running setup.py bdist_wheel for nf-core ... done
  Stored in directory: /Users/oren/Library/Caches/pip/wheels/07/58/3a/891755fa8288bb3e7d8013941ef13d1abf479513c7fdade5f3
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /Users/oren/Library/Caches/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
  Running setup.py bdist_wheel for tabulate ... done
  Stored in directory: /Users/oren/Library/Caches/pip/wheels/2a/85/33/2f6da85d5f10614cbe5a625eab3b3aebfdf43e7b857f25f829
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /Users/oren/Library/Caches/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
  Running setup.py bdist_wheel for arrow ... done
  Stored in directory: /Users/oren/Library/Caches/pip/wheels/a3/dd/b2/d3b8d22e8136164c2e2c36ed42392531957cdf9c717065b28b
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /Users/oren/Library/Caches/pip/wheels/33/56/20/ebe49a5c612fffe1c5a632146b16596f9e64676768661e4e46
Successfully built nf-core pyyaml tabulate future arrow MarkupSafe
Installing collected packages: click, poyo, future, certifi, urllib3, chardet, idna, requests, binaryornot, six, python-dateutil, arrow, MarkupSafe, jinja2, jinja2-time, whichcraft, cookiecutter, smmap2, gitdb2, GitPython, pyyaml, requests-cache, tabulate, nf-core
Successfully installed GitPython-2.1.11 MarkupSafe-1.0 arrow-0.12.1 binaryornot-0.4.4 certifi-2018.8.24 chardet-3.0.4 click-7.0 cookiecutter-1.6.0 future-0.16.0 gitdb2-2.0.4 idna-2.7 jinja2-2.10 jinja2-time-0.2.0 nf-core-1.2 poyo-0.4.2 python-dateutil-2.7.3 pyyaml-3.13 requests-2.19.1 requests-cache-0.4.13 six-1.11.0 smmap2-2.0.4 tabulate-0.8.2 urllib3-1.23 whichcraft-0.4.1
Orens-MacBook-Pro:nf-core-tools oren$ pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git
-bash: pip: command not found
Orens-MacBook-Pro:nf-core-tools oren$ pip3 install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git
Collecting git+https://github.com/nf-core/tools.git
  Cloning https://github.com/nf-core/tools.git to /private/var/folders/rq/6p966k9971g8lfz6wx5w5z140000gn/T/pip-req-build-xy_c3ret
Collecting cookiecutter (from nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1.6.0-py2.py3-none-any.whl
Collecting click (from nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting GitPython (from nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl
Collecting pyyaml (from nf-core==1.2)
Collecting requests (from nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting requests_cache (from nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/00/62/9e45a38988cb48c474805a1626439f4d9a486a042bd077af888fa8b17a64/requests_cache-0.4.13-py2.py3-none-any.whl
Collecting tabulate (from nf-core==1.2)
Collecting jinja2-time>=0.1.0 (from cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl
Collecting future>=0.15.2 (from cookiecutter->nf-core==1.2)
Collecting jinja2>=2.7 (from cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting binaryornot>=0.2.0 (from cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting whichcraft>=0.4.0 (from cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/60/8a/5c52e30e11672f7e3aa61f348ddae443d122bcd96bc8b785ac76dbae944b/whichcraft-0.4.1-py2.py3-none-any.whl
Collecting poyo>=0.1.0 (from cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/e0/16/e00e3001007a5e416ca6a51def6f9e4be6a774bf1c8486d20466f834d113/poyo-0.4.2-py2.py3-none-any.whl
Collecting gitdb2>=2.0.0 (from GitPython->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/a9/fb/d3afc4e2a8d506a07af19f125f7a473ae1b56f942ed2ba80776eb8ae23b1/gitdb2-2.0.4-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting arrow (from jinja2-time>=0.1.0->cookiecutter->nf-core==1.2)
Collecting MarkupSafe>=0.23 (from jinja2>=2.7->cookiecutter->nf-core==1.2)
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/0f/14/e3112808b727f72df9531fc2f00b84d4966e66001748b6883a21c767e902/smmap2-2.0.4-py2.py3-none-any.whl
Collecting python-dateutil (from arrow->jinja2-time>=0.1.0->cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->arrow->jinja2-time>=0.1.0->cookiecutter->nf-core==1.2)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: nf-core
  Running setup.py bdist_wheel for nf-core ... done
  Stored in directory: /private/var/folders/rq/6p966k9971g8lfz6wx5w5z140000gn/T/pip-ephem-wheel-cache-_0lo2wqa/wheels/7a/9d/0f/4fcfdede2e3c1932daacd92094f522c161c60d9060c6630f7c
Successfully built nf-core
Installing collected packages: MarkupSafe, jinja2, six, python-dateutil, arrow, jinja2-time, future, chardet, idna, urllib3, certifi, requests, binaryornot, whichcraft, poyo, click, cookiecutter, smmap2, gitdb2, GitPython, pyyaml, requests-cache, tabulate, nf-core
  Found existing installation: MarkupSafe 1.0
    Uninstalling MarkupSafe-1.0:
      Successfully uninstalled MarkupSafe-1.0
  Found existing installation: Jinja2 2.10
    Uninstalling Jinja2-2.10:
      Successfully uninstalled Jinja2-2.10
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: python-dateutil 2.7.3
    Uninstalling python-dateutil-2.7.3:
      Successfully uninstalled python-dateutil-2.7.3
  Found existing installation: arrow 0.12.1
    Uninstalling arrow-0.12.1:
      Successfully uninstalled arrow-0.12.1
  Found existing installation: jinja2-time 0.2.0
    Uninstalling jinja2-time-0.2.0:
      Successfully uninstalled jinja2-time-0.2.0
  Found existing installation: future 0.16.0
    Uninstalling future-0.16.0:
      Successfully uninstalled future-0.16.0
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Found existing installation: idna 2.7
    Uninstalling idna-2.7:
      Successfully uninstalled idna-2.7
  Found existing installation: urllib3 1.23
    Uninstalling urllib3-1.23:
      Successfully uninstalled urllib3-1.23
  Found existing installation: certifi 2018.8.24
    Uninstalling certifi-2018.8.24:
      Successfully uninstalled certifi-2018.8.24
  Found existing installation: requests 2.19.1
    Uninstalling requests-2.19.1:
      Successfully uninstalled requests-2.19.1
  Found existing installation: binaryornot 0.4.4
    Uninstalling binaryornot-0.4.4:
      Successfully uninstalled binaryornot-0.4.4
  Found existing installation: whichcraft 0.4.1
    Uninstalling whichcraft-0.4.1:
      Successfully uninstalled whichcraft-0.4.1
  Found existing installation: poyo 0.4.2
    Uninstalling poyo-0.4.2:
      Successfully uninstalled poyo-0.4.2
  Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
  Found existing installation: cookiecutter 1.6.0
    Uninstalling cookiecutter-1.6.0:
      Successfully uninstalled cookiecutter-1.6.0
  Found existing installation: smmap2 2.0.4
    Uninstalling smmap2-2.0.4:
      Successfully uninstalled smmap2-2.0.4
  Found existing installation: gitdb2 2.0.4
    Uninstalling gitdb2-2.0.4:
      Successfully uninstalled gitdb2-2.0.4
  Found existing installation: GitPython 2.1.11
    Uninstalling GitPython-2.1.11:
      Successfully uninstalled GitPython-2.1.11
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Found existing installation: requests-cache 0.4.13
    Uninstalling requests-cache-0.4.13:
      Successfully uninstalled requests-cache-0.4.13
  Found existing installation: tabulate 0.8.2
    Uninstalling tabulate-0.8.2:
      Successfully uninstalled tabulate-0.8.2
  Found existing installation: nf-core 1.2
    Uninstalling nf-core-1.2:
      Successfully uninstalled nf-core-1.2
Successfully installed GitPython-2.1.11 MarkupSafe-1.0 arrow-0.12.1 binaryornot-0.4.4 certifi-2018.8.24 chardet-3.0.4 click-7.0 cookiecutter-1.6.0 future-0.16.0 gitdb2-2.0.4 idna-2.7 jinja2-2.10 jinja2-time-0.2.0 nf-core-1.2 poyo-0.4.2 python-dateutil-2.7.3 pyyaml-3.13 requests-2.19.1 requests-cache-0.4.13 six-1.11.0 smmap2-2.0.4 tabulate-0.8.2 urllib3-1.23 whichcraft-0.4.1
```

</details>

Rest of commands:

```
Orens-MacBook-Pro:nf-core-tools oren$ nf-core list

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'
    
Traceback (most recent call last):
  File "/usr/local/bin/nf-core", line 198, in <module>
    nf_core_cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/nf-core", line 70, in list
    nf_core.list.list_workflows(sort, json, keywords)
  File "/usr/local/lib/python3.7/site-packages/nf_core/list.py", line 35, in list_workflows
    wfs.get_local_nf_workflows()
  File "/usr/local/lib/python3.7/site-packages/nf_core/list.py", line 83, in get_local_nf_workflows
    nflist_raw = subprocess.check_output(['nextflow', 'list'], stderr=devnull)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nextflow': 'nextflow'
```

```
Orens-MacBook-Pro:nf-core-tools oren$ pwd
/Users/oren/VIB/DATA_INTEGRATION/NextFlow/nf-core-tools
```
```
Orens-MacBook-Pro:nf-core-tools oren$ ls -ltr
total 72
-rw-r--r--   1 oren  staff   3286 Oct  9 19:40 CHANGELOG.md
-rw-r--r--   1 oren  staff    357 Oct  9 19:40 Dockerfile
-rw-r--r--   1 oren  staff   1064 Oct  9 19:40 LICENSE
-rw-r--r--   1 oren  staff     62 Oct  9 19:40 MANIFEST.in
-rw-r--r--   1 oren  staff  12381 Oct  9 19:40 README.md
drwxr-xr-x   4 oren  staff    128 Oct  9 19:40 bin
drwxr-xr-x   4 oren  staff    128 Oct  9 19:40 docs
drwxr-xr-x  11 oren  staff    352 Oct  9 19:40 nf_core
drwxr-xr-x   3 oren  staff     96 Oct  9 19:40 scripts
-rw-r--r--   1 oren  staff   1154 Oct  9 19:40 setup.py
drwxr-xr-x   7 oren  staff    224 Oct  9 19:40 tests
```
```
Orens-MacBook-Pro:nf-core-tools oren$ ls nf_core/
__init__.py		create.py		licences.py		list.py			utils.py
bump_version.py		download.py		lint.py			pipeline-template
```
```
Orens-MacBook-Pro:nf-core-tools oren$ nf-core list

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'
    
Traceback (most recent call last):
  File "/usr/local/bin/nf-core", line 198, in <module>
    nf_core_cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/nf-core", line 70, in list
    nf_core.list.list_workflows(sort, json, keywords)
  File "/usr/local/lib/python3.7/site-packages/nf_core/list.py", line 35, in list_workflows
    wfs.get_local_nf_workflows()
  File "/usr/local/lib/python3.7/site-packages/nf_core/list.py", line 83, in get_local_nf_workflows
    nflist_raw = subprocess.check_output(['nextflow', 'list'], stderr=devnull)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nextflow': 'nextflow'
```

**Comment by ewels** [comment]
I updated your comment with some markdown tricks to try to make it a little more readable, hope that's ok @vibbits.

As @sven1103 asked on gitter:

> @vibbits would you mind opening a python3.7 console and enter this:
> ```python
> import os
> print(os.getenv('PATH'))
> ```
> and afterwards from your terminal: `which nextflow`

However, irrespective of what is causing this, we should definitely handle the problem in a nicer manner with a better error message 👍 

Phil

**Comment by vibbits** [comment]
Thanks guys. I tried as suggested and in python 3.7 did:
```
import os
print(os.getenv('PATH'))
```
And got: 
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```
However, coming back to the terminal and asking 
```
which nextflow
```
yields empty output...

**Comment by ewels** [comment]
Thanks @vibbits - so this looks like nextflow isn't installed.. But you said it was? How do you normally run nextflow if the command is not available on the `PATH`?

**Comment by sven1103** [comment]
You have to install `Nextflow` properly, like written on their website: [https://www.nextflow.io/docs/latest/getstarted.html#installation](https://www.nextflow.io/docs/latest/getstarted.html#installation).

Pip is a Python package manager, thus you cannot install `Nextflow` via pip.

After you installed Nextflow properly, the executable will be in your `PATH` variable scope, and `nf-core` will work properly.

Best, Sven

**Comment by apeltzer** [comment]
If you're on OSX, install Java first: https://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by ewels** [comment]
> I should say I never used nextflow before, but based on the installation commands log (see above), I thought I did managed to install nf with pip3. So I guess the installation did not succeed? Is there a way to debug my installation?

Ah, I think maybe you missed that `nf-core` and `nextflow` are separate tools perhaps? The Python `nf-core` tools package is a bunch of helper scripts to make it easier to use and develop [nf-core](https://nf-co.re/) pipelines. This is totally separate from [nextflow](https://www.nextflow.io/) itself, which is the package that actually does all the hard work :)

Our "getting started" documentation may be helpful: https://nf-co.re/usage_docs

**Comment by vibbits** [comment]
Indeed this threw me off. Now im on top of things. Thanks a lot!

**Comment by sven1103** [comment]
@vibbits does this mean that it works now?

**Comment by vibbits** [comment]
Yes. Please ignore my last comment @sven1103 
it was solved by adding the full path of the folder before executing nextflow.
Cheers!
