### ISSUE TITLE
TypeError after running `nf-core`

### ISSUE THREAD

**Issue by subwaystation** [nf-core/tools#1811]
### Description of the bug

I just want to run the nf-core tools, but it immediately crashes.

### Command used and terminal output

```console
nf-core
Traceback (most recent call last):
  File "/home/heumos/.local/bin/nf-core", line 5, in <module>
    from nf_core.__main__ import run_nf_core
  File "/home/heumos/.local/lib/python3.10/site-packages/nf_core/__main__.py", line 14, in <module>
    import nf_core.bump_version
  File "/home/heumos/.local/lib/python3.10/site-packages/nf_core/bump_version.py", line 12, in <module>
    import nf_core.utils
  File "/home/heumos/.local/lib/python3.10/site-packages/nf_core/utils.py", line 24, in <module>
    import requests_cache
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/__init__.py", line 43, in <module>
    from .backends import *
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 8, in <module>
    from .base import BaseCache, BaseStorage
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 6, in <module>
    from .preconf import (
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/serializers/preconf.py", line 26, in <module>
    base_stage = CattrStage()  #: Base stage for all serializer pipelines
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 32, in __init__
    self.converter = init_converter(factory)
  File "/home/heumos/.local/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 67, in init_converter
    converter.register_structure_hook(
  File "/home/heumos/.local/lib/python3.10/site-packages/cattr/converters.py", line 269, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/home/heumos/.local/lib/python3.10/site-packages/cattr/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/usr/lib/python3.10/functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class.
```

### System information

- nextflow version 22.04.5.5708
- laptop with Ryzen7 
- ArchLinux
- nf-core/tools: I just installed the most recent one with pip, 2.5.1.
- Python version 3.10

**Comment by subwaystation** [comment]
Thanks to @mirpedrol for coming up with the solution: Just update `requests_cache` with `pip install requests_cache -U --user`.
