### ISSUE TITLE
nf-core tools in docker is broken

### ISSUE THREAD

**Issue by pontus** [nf-core/tools#1911]
### Description of the bug

Tools does not handle failure to create `.config` directory as it should. Lacking a proper `$HOME` it will default to / and try to create `/.config`

### Command used and terminal output

```console
pontus@atra:~$ docker run -itv `pwd`:`pwd` -w `pwd` -u $(id -u):$(id -g) nfcore/tools
Traceback (most recent call last):
  File "/usr/local/bin/nf-core", line 5, in <module>
    from nf_core.__main__ import run_nf_core
  File "/usr/local/lib/python3.8/site-packages/nf_core/__main__.py", line 31, in <module>
    nf_core.utils.setup_nfcore_dir()
  File "/usr/local/lib/python3.8/site-packages/nf_core/utils.py", line 310, in setup_nfcore_dir
    os.makedirs(NFCORE_DIR)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
pontus@atra:~$
```

**Comment by scott-lsbdt** [comment]
I'm having the same issue, do you have a solution @pontus ?

**Comment by pontus** [comment]
Yes, simply pointing HOME somewhere writable will get you through, e.g. adding `-e HOME=/tmp`.

**Comment by scott-lsbdt** [comment]
@pontus Ah its as simple as that! Thanks for the fix.

**Comment by Dan2389** [comment]
Hi, i'm having the same identical problem, but the solution you gave is not working for me, do you have any other suggestion? thanks!

**Comment by Dan2389** [comment]
ok, solved it. I was putting it at the end, but moving the -e before the -w made the trick. Thanks!

**Comment by mashehu** [comment]
Would adding `$HOME=/root` to the dockerfile solve this issue?

**Comment by pontus** [comment]
No, that would cause the same kind of breakage as we already see. When running as root the current setup works (excluding side-effects like permissions of files created).

In fact, I'd rather expect it would break running this with singularity (where `$HOME` is typically set correctly).

**Comment by kumarage** [comment]
Hi @pontus,

I am using a remote instance of HTCondor and following their guide to place the https://hub.docker.com/r/nfcore/tools/tags docker. It gave me the same error message although I used "export HOME=$PWD". I dd above too but none of them worked and gave me

"Traceback (most recent call last):
  File "/usr/local/bin/nf-core", line 5, in <module>
    from nf_core.__main__ import run_nf_core
  File "/usr/local/lib/python3.11/site-packages/nf_core/__main__.py", line 24, in <module>
    setup_nfcore_dir()
  File "/usr/local/lib/python3.11/site-packages/nf_core/utils.py", line 326, in setup_nfcore_dir
    os.makedirs(NFCORE_DIR)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/.config'"

**Comment by pontus** [comment]
I'm not sure what command you used but if running with `docker`, it won't help changing the environment outside. Rather you need to pass the environment you want to be seen explicitly e.g. with `-e`>

**Comment by aowen-uwmad** [comment]
I'm at the site that @kumarage mentioned. They were using the "container universe" of HTCondor to run the Docker container. In this case, we had to use the `environment` command in the [HTCondor submit file](https://htcondor.readthedocs.io/en/latest/man-pages/condor_submit.html#:~:text=environment%20%3D%20%3Cparameter_list%3E). This in turn passes the environment variables to the docker run command that is executed by HTCondor, using the `-e` option.

```
# HTCondor submit file
universe = container
container_image = docker://nfcore/tools:latest

environment = "HOME=$$(CondorScratchDir))"
arguments = "list rna-seq"
...
```

**Comment by pontus** [comment]
I'd prefer leaving this open, it's still broken.
