### ISSUE TITLE
Linting errors / package? 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#192]
```
Traceback (most recent call last):
  File "/home/travis/.local/bin/nf-core", line 4, in <module>
    __import__('pkg_resources').require('nf-core==1.2')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.18.0'), set(['cookiecutter']))
The command "nf-core lint ${TRAVIS_BUILD_DIR}" exited with 1.

```

**Comment by apeltzer** [comment]
e.g. in https://travis-ci.org/nf-core/rrna-ampliseq/jobs/453679656

**Comment by apeltzer** [comment]
Should add it to the template then to sync it :)

**Comment by apeltzer** [comment]
Will open a PR for that

**Comment by sven1103** [comment]
will leave it open, until the PR is merged. sry
