### ISSUE TITLE
Code possibly not covered by CI

### ISSUE THREAD

**Issue by remiolsen** [nf-core/tools#20]
Here's how to reproduce the bugs referenced in #19 

-----

`python --version`
```
Python 3.6.3 :: Anaconda, Inc.
```

```
git clone https://github.com/SciLifeLab/NGI-NeutronStar.git
cd NGI-NeutronStar
git reset --hard 59bfe4e717419d1e3667422cd486071073b41bcd
nf-core lint .
```
```python
Traceback (most recent call last):
  File "/Users/remi-andreolsen/miniconda3/envs/py3/bin/nf-core", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/remi-andreolsen/code/nf-core-tools/scripts/nf-core", line 10, in <module>
    import nf_core.lint
  File "/Users/remi-andreolsen/code/nf-core-tools/nf_core/lint.py", line 272
    except AssertionError, KeyError:
                         ^
SyntaxError: invalid syntax
```

### Add paranthesis to except statement

`nf-core lint .`
```
Running pipeline tests  [######------------------------------]   16%
```
```python
Traceback (most recent call last):
  File "/Users/remi-andreolsen/miniconda3/envs/py3/bin/nf-core", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/remi-andreolsen/code/nf-core-tools/scripts/nf-core", line 50, in <module>
    nf_core_cli()
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/remi-andreolsen/code/nf-core-tools/scripts/nf-core", line 34, in lint
    lint_obj.lint_pipeline()
  File "/Users/remi-andreolsen/code/nf-core-tools/nf_core/lint.py", line 64, in lint_pipeline
    getattr(self, fname)()
  File "/Users/remi-andreolsen/code/nf-core-tools/nf_core/lint.py", line 107, in check_files_exist
    self.files.append(f)
NameError: name 'f' is not defined
```

### Change `f` -> `files`

```
git reset --hard c92ce0d99baff39bfcbb36c64be03160dc0331f8
touch .travis.yml CHANGELOG.MD docs/README.md docs/output.md docs/usage.md
nf-core lint .

Running pipeline tests  [########################------------]   66%
```
```python
Traceback (most recent call last):
  File "/Users/remi-andreolsen/miniconda3/envs/py3/bin/nf-core", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/remi-andreolsen/code/nf-core-tools/scripts/nf-core", line 50, in <module>
    nf_core_cli()
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/remi-andreolsen/miniconda3/envs/py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/remi-andreolsen/code/nf-core-tools/scripts/nf-core", line 34, in lint
    lint_obj.lint_pipeline()
  File "/Users/remi-andreolsen/code/nf-core-tools/nf_core/lint.py", line 64, in lint_pipeline
    getattr(self, fname)()
  File "/Users/remi-andreolsen/code/nf-core-tools/nf_core/lint.py", line 213, in check_config_vars
    k, v = l.split(' = ', 1)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by sven1103** [comment]
Thank you Remi, I can reproduce this in Python 3.6.4 too. It seems that the Travis build does use the default Python version of Ubuntu trusty (https://packages.ubuntu.com/trusty/python/python) which is 2.7.5. 

The Python versions we defined in the `.travis.yml` seem to be ignored, which is why the build did not fail until now.

I will merge your PR, but the issue should remain open imo, until we resoved this.

Thanks again for bringing that up!
