### ISSUE TITLE
Using the nfcore/tools docker image gets permission denied now

### ISSUE THREAD

**Issue by thondeboer** [nf-core/tools#2944]
### Description of the bug

I'm using the docker image nfcore/tools to develop my pipelines and run schema build, but lately I am getting a permission denied issue when running the docker version.

### Command used and terminal output

```console
docker run -itv `pwd`:`pwd` -w `pwd` -u $(id -u):$(id -g) nfcore/tools
Unable to find image 'nfcore/tools:latest' locally
latest: Pulling from nfcore/tools
e1caac4eb9d2: Pull complete 
51d1f07906b7: Pull complete 
fe87ad6b112e: Pull complete 
4d8ccb72bbad: Pull complete 
8100581c78dd: Pull complete 
7bfcabf371be: Pull complete 
ffe7d43d52f3: Pull complete 
4cf8394fe5e8: Pull complete 
4a9ae2a4dd52: Pull complete 
131ad79d069d: Pull complete 
40be4339f485: Pull complete 
70a19b5b9798: Pull complete 
08030602159c: Pull complete 
4f4fb700ef54: Pull complete 
ec15d696e163: Pull complete 
Digest: sha256:bf01e0890530576a543885d348642901e4b6252d9029108c8552fd6502e4b4de
Status: Downloaded newer image for nfcore/tools:latest
Could not create cache directory: /.cache/nfcore/cache_3.11.8
Traceback (most recent call last):
  File "/usr/local/bin/nf-core", line 5, in <module>
    from nf_core.__main__ import run_nf_core
  File "/usr/local/lib/python3.11/site-packages/nf_core/__main__.py", line 26, in <module>
    setup_nfcore_dir()
  File "/usr/local/lib/python3.11/site-packages/nf_core/utils.py", line 340, in setup_nfcore_dir
    os.makedirs(NFCORE_DIR)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/.config'
```

### System information

Nextflow verison 23.10.1
Docker version 24.0.6, build ed223bc

**Comment by Skitionek** [comment]
Just run without user flag ` docker run -itv `pwd`:`pwd` -w `pwd` nfcore/tools`
