### ISSUE TITLE
nf-core list: Handle exception when HEAD is detached

### ISSUE THREAD

**Issue by Zethson** [nf-core/tools#297]
```console
(base) [zeth@master course]$ nf-core list

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'
```
```python
Traceback (most recent call last):
  File "/home/zeth/anaconda3/bin/nf-core", line 239, in <module>
    nf_core_cli()
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zeth/anaconda3/bin/nf-core", line 72, in list
    nf_core.list.list_workflows(sort, json, keywords)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/nf_core/list.py", line 36, in list_workflows
    wfs.get_local_nf_workflows()
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/nf_core/list.py", line 112, in get_local_nf_workflows
    wf.get_local_nf_workflow_details()
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/nf_core/list.py", line 298, in get_local_nf_workflow_details
    self.branch = str(repo.active_branch)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/git/repo/base.py", line 696, in active_branch
    return self.head.reference
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/git/refs/symbolic.py", line 275, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '124cbbe5a070e1ee1dec25da1f65c9baea179b91'
```

I guess there's an issue with a git branch?

**Comment by ewels** [comment]
No worries - GitHub has a new feature which allows you to transfer issues, so I've just moved this to tools.

Relevant code: _(problem is line 298)_ https://github.com/nf-core/tools/blob/1855d346a8f1c4b839ab7d2264212edc478e1912/nf_core/list.py#L293-L301

Can you rerun with verbose logging please? `nf-core -v list`

Also, if you can go through all of your nf-core repos that have been pulled by nextflow and check their git statuses:

```bash
cd ~/.nextflow/assets/nf-core/
cd rnaseq/
git status
# ..etc
```

My guess is that one of these will give the same detached status. I'm not sure how this could have happened - we should add some code to the listing command to handle this exception type though.

If you want to solve this, just reset the repo that has the detached head:
```bash
git reset --hard HEAD
```

Then I think everything should work fine again.

Phil

**Comment by Zethson** [comment]
`(base) [zeth@master ~]$ nf-core -v list

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'


DEBUG: Fetching list of nf-core workflows

DEBUG: Guessed nextflow assets directory - pulling nf-core dirnames

DEBUG: Fetching extra info about 1 local workflows

DEBUG: Guessed nextflow assets workflow directory

DEBUG: Popen(['git', 'cat-file', '--batch-check'], cwd=/home/zeth/.nextflow/assets/nf-core/mhcquant, universal_newlines=False, shell=None)
Traceback (most recent call last):
  File "/home/zeth/anaconda3/bin/nf-core", line 239, in <module>
    nf_core_cli()
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zeth/anaconda3/bin/nf-core", line 72, in list
    nf_core.list.list_workflows(sort, json, keywords)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/nf_core/list.py", line 36, in list_workflows
    wfs.get_local_nf_workflows()
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/nf_core/list.py", line 112, in get_local_nf_workflows
    wf.get_local_nf_workflow_details()
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/nf_core/list.py", line 298, in get_local_nf_workflow_details
    self.branch = str(repo.active_branch)
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/git/repo/base.py", line 696, in active_branch
    return self.head.reference
  File "/home/zeth/anaconda3/lib/python3.7/site-packages/git/refs/symbolic.py", line 275, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '124cbbe5a070e1ee1dec25da1f65c9baea179b91'
`

**Comment by Zethson** [comment]
I only have MHCQuant on my machine.
There is no detached head in this repository. But certainly it's related to this.

The debug log shows:
```
cwd=/home/zeth/.nextflow/assets/nf-core/mhcquant
```

**Comment by Zethson** [comment]
Removing 
```
.nextflow/assets/nf-core/mhcquant
```
solved the issue.

**Comment by ewels** [comment]
Is there anything to fix here? I’m a bit lost as to what the issue is that needs solving..

**Comment by Zethson** [comment]
I accidentally reproduced it a month later or so, but it might just be an issue with my setup. No idea.
You can close this I guess.

**Comment by ewels** [comment]
Thinking about it more... I would guess that this happens when nextflow pulls a workflow to your home directory cache (`nextflow run nf-core/pipeline` or `nextflow pull nf-core/pipeline` ), and then you rebase and force-push commits to that repo. This would result in the nextflow version being detached.

This has happened before and broken the website, which pulls the tools repo and others. That's why that update script now forces a hard `git reset` every time: https://github.com/nf-core/nf-co.re/blob/e000fde00471a483715cba0ac80b37f8ef26821b/public_html/deploy.php#L14-L15

```bash
git fetch && git reset --hard origin/master
```

This _shouldn't_ really happen, as `master` should always be super stable. But now I can see why it might happen, I figure we should probably be defensive and handle the exception. Should be easy enough to do..
