### ISSUE TITLE
Rendering with current markdown version

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#571]
When using the latest (V1.9) template, we replaced the R code with a Python script. This is broken when updating the `markdown` package in the container used for any pipeline and results in e.g. errors like this:

```bash
  Traceback (most recent call last):
    File "/Users/alexanderpeltzer/Downloads/eager/bin/markdown_to_html.py", line 100, in <module>
      sys.exit(main())
    File "/Users/alexanderpeltzer/Downloads/eager/bin/markdown_to_html.py", line 95, in main
      converted_md = convert_markdown(args.mdfile.name)
    File "/Users/alexanderpeltzer/Downloads/eager/bin/markdown_to_html.py", line 28, in convert_markdown
      'title': 'Table of Contents'
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/markdown/core.py", line 387, in markdown
      md = Markdown(**kwargs)
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/markdown/core.py", line 97, in __init__
      configs=kwargs.get('extension_configs', {}))
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/markdown/core.py", line 125, in registerExtensions
      ext._extendMarkdown(self)
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/markdown/extensions/__init__.py", line 77, in _extendMarkdown
      self.extendMarkdown(md)
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/pymdownx/extra.py", line 60, in extendMarkdown
      md.registerExtensions(extra_extensions, self.config)
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/markdown/core.py", line 125, in registerExtensions
      ext._extendMarkdown(self)
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/markdown/extensions/__init__.py", line 77, in _extendMarkdown
      self.extendMarkdown(md)
    File "/opt/conda/envs/nf-core-eager-2.1.0dev/lib/python3.7/site-packages/pymdownx/extrarawhtml.py", line 30, in extendMarkdown
      extra.MarkdownInHtmlProcessor(md.parser), 'markdown_block', 105
  AttributeError: module 'markdown.extensions.extra' has no attribute 'MarkdownInHtmlProcessor'
```

**Comment by apeltzer** [comment]
Not directly related to this here https://github.com/nf-core/tools/issues/391 but could be fixed in the same go ;-)

**Comment by phue** [comment]
Just for reference:
This issue was fixed in https://github.com/facelessuser/pymdown-extensions/commit/f17ba7b5e05eaa5b32c2f1ef0ce78dcae0339bb9#diff-1915e1d5e453671c14bd0dd5ab7a2b1f
So once pymdown-extensions 7.0.0 hits the conda-forge repos it should also work with newer markdown versions

**Comment by ewels** [comment]
Nice, good find @phue - if they are depreciating something does that mean that we should update a method we're using somewhere? Though I think we're not actually using that method, so I guess it's only a cross-package compatibility thing and we're fine..

**Comment by ewels** [comment]
Hmm, looks like the feedstock for this package is a little out of love: https://github.com/conda-forge/pymdown-extensions-feedstock/pulls

**Comment by apeltzer** [comment]
Yeah :-(

**Comment by ewels** [comment]
Have bumped the version and re-rendered with conda smithy. Hopefully that will fix it. At least the Azure builds will still be there if it fails so that we can see what is going wrong..

https://github.com/conda-forge/pymdown-extensions-feedstock/pull/5

**Comment by ewels** [comment]
ok, tests are passing so it should be good to merge ✅  - just needs someone to merge it now 🤞

**Comment by ewels** [comment]
I pinged the conda-forge core team and got myself added as a maintainer, so the above PR was merged and hopefully we can move this forward now..

**Comment by drpatelh** [comment]
This should be fixed now.
